# Generated by Django 5.2.7 on 2025-10-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public_did',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_key',
        ),
    ]
