# Generated by Django 5.2.7 on 2025-10-16 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_user_public_did_remove_user_wallet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='CredentialIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_exchange_id', models.CharField(max_length=255)),
                ('credential_definition_id', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('proposal_sent', 'Proposal Sent'), ('proposal_received', 'Proposal Received'), ('offer_sent', 'Offer Sent'), ('offer_received', 'Offer Received'), ('request_sent', 'Request Sent'), ('request_received', 'Request Received'), ('credential_issued', 'Credential Issued'), ('credential_received', 'Credential Received'), ('done', 'Done'), ('abandoned', 'Abandoned')], max_length=20)),
                ('attributes', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.connection')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
