# Generated by Django 5.2.7 on 2026-05-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_wallet_object_id_credentialissuance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_key',
            new_name='agent_admin_url',
        ),
    ]
