services:
  postgres:
    image: postgres:13
    container_name: aca-py-postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: "acapy_wallet" # Solo una base de datos
      POSTGRES_USER: acapy_user
      POSTGRES_PASSWORD: acapy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U acapy_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  aca-py:
    image: bcgovimages/aries-cloudagent:py3.12_1.2.0
    container_name: aca-py-agent
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9030:9030"
      - "9031:9031"
      # - "3000:3000"
      # - "3001:3001"
    volumes:
      - ./genesis.txn:/home/indy/genesis.txn
    command: >
      start
      --endpoint http://localhost:9000
      --label "Agent with Local Genesis"
      --inbound-transport http 0.0.0.0 9000
      --outbound-transport http
      --admin 0.0.0.0 9031
      --admin-insecure-mode
      --genesis-file /home/indy/genesis.txn
      --seed 000000000000000000000000Trustee1 
      --multitenant
      --multitenant-admin
      --jwt-secret "a2af09aa66bbea6806fead4d8816debf04d4e8d63cba823e8e376b240da149a6391f35989a09190b2be91cc2eb7bb1e4abee1ca7e366ed63545947241222cc98"
      --wallet-type askar
      --wallet-name postgres_wallet
      --wallet-key walletkey123
      --wallet-storage-type postgres_storage
      --wallet-storage-config '{"url":"postgres:5432/acapy_wallet","max_connections":5}'
      --wallet-storage-creds '{"account":"acapy_user","password":"acapy_password","admin_account":"acapy_user","admin_password":"acapy_password"}'
      --auto-provision
      --auto-accept-invites
      --auto-accept-requests
      --log-level INFO

volumes:
  postgres_data:
